### PR TITLE
add new courses to database section

### PR DESCRIPTION
**Pull request by CouchofTomato**
This adds the lessons for the database mini-course

### CODE REVIEW

**Comment by KevinMulhern** [comment]
👍 looks good

**Comment by leosoaivan** [comment]
:+1:  Thanks for putting this together @CouchofTomato

**Comment by CouchofTomato** [comment]
Am I good to merge this now so I can set up the course in the seeds file?

**Comment by KevinMulhern** [comment]
Lets do it 🎉

**Pull request merged**
